name = "nerzov-platform"
compatibility_date = "2026-08-25"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "nerzov-db"
database_id = "0bf4fc48-720b-45e2-865a-f2374d57c421"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "nerzov-assets"
